/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.JSoundsMainWindowViewController;
import javax.swing.JTextField;
import jmusic.JMusicPlayerList;

/**
 * @author Anibal Dominguez
 * @author Manuel Pacheco
 * @author José Suárez
 */
public class EditSongWindow extends MyOwnJFrame {
    
    public static String songName;
    public static String artistEdit;
    public static String albumEdit;
    public static String genderEdit;
    public static int index;
    public static JMusicPlayerList list;

    /**
     * Creates new form EditSongWindow
     */
    public EditSongWindow() {
        initComponents();
        setTextToEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNameSong = new javax.swing.JLabel();
        jlGenderSong = new javax.swing.JLabel();
        jlNumberSong = new javax.swing.JLabel();
        jtfEditSongName = new javax.swing.JTextField();
        jtfEditSongGender = new javax.swing.JTextField();
        jtfEditSongNumber = new javax.swing.JTextField();
        jlArtistSongEdit = new javax.swing.JLabel();
        jtfEditSongArtist = new javax.swing.JTextField();
        jlAlbumSongEdit = new javax.swing.JLabel();
        jtfEditSongAlbum = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jlYearSong = new javax.swing.JLabel();
        jtfEditSongYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlNameSong.setText("Name");

        jlGenderSong.setText("Gender");

        jlNumberSong.setText("Number");

        jtfEditSongNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfEditSongNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditSongNumberActionPerformed(evt);
            }
        });

        jlArtistSongEdit.setText("Artist");

        jlAlbumSongEdit.setText("Album");

        jbOk.setText("Ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jlYearSong.setText("Year");

        jtfEditSongYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlGenderSong)
                    .addComponent(jlAlbumSongEdit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNameSong)
                        .addComponent(jlArtistSongEdit))
                    .addComponent(jlYearSong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfEditSongName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEditSongArtist, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEditSongGender, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEditSongAlbum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfEditSongYear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNumberSong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfEditSongNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditSongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNameSong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditSongArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlArtistSongEdit))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditSongAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAlbumSongEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditSongGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGenderSong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditSongYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlYearSong)
                    .addComponent(jtfEditSongNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumberSong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbCancel))
                .addGap(49, 49, 49))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-381)/2, (screenSize.height-305)/2, 381, 305);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEditSongNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditSongNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditSongNumberActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
            JSoundsMainWindowViewController.editSong(list, index, jtfEditSongName.getText(), jtfEditSongArtist.getText(), jtfEditSongAlbum.getText() , jtfEditSongNumber.getText());
            restoreFatherWindow();
            dispose();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        restoreFatherWindow();
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
             restoreFatherWindow();
             dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSongWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSongWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSongWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSongWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSongWindow().setVisible(true);
            }
        });       

    }


    
    
    
    public static void setTextToEdit()
    {
        jtfEditSongName.setText(songName);
        jtfEditSongArtist.setText(artistEdit);
        jtfEditSongAlbum.setText(albumEdit);
        jtfEditSongGender.setText(genderEdit);
        jtfEditSongYear.setText ("2012");
        jtfEditSongNumber.setText (ViewUtilFunctions.integerToString(1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlAlbumSongEdit;
    private javax.swing.JLabel jlArtistSongEdit;
    private javax.swing.JLabel jlGenderSong;
    private javax.swing.JLabel jlNameSong;
    private javax.swing.JLabel jlNumberSong;
    private javax.swing.JLabel jlYearSong;
    public static javax.swing.JTextField jtfEditSongAlbum;
    public static javax.swing.JTextField jtfEditSongArtist;
    public static javax.swing.JTextField jtfEditSongGender;
    public static javax.swing.JTextField jtfEditSongName;
    public static javax.swing.JTextField jtfEditSongNumber;
    public static javax.swing.JTextField jtfEditSongYear;
    // End of variables declaration//GEN-END:variables
}
