/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.JSoundsMainWindowViewController;

/**
 * @author Anibal Dominguez
 * @author Manuel Pacheco
 * @author José Suárez
 */
public class PlaylistChooser extends MyOwnJFrame{

    public static boolean loadPlaylist=false;
    /**
     * Creates new form PlaylistSelector
     */
    public PlaylistChooser() {
        initComponents();
        initMyOwnComponents();
    }
    
    private void initMyOwnComponents()
    {
        JSoundsMainWindowViewController.loadAllPlaylistInCombo(jcbChoosePlaylist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbChoosePlaylist = new javax.swing.JComboBox();
        jbPlaylistOk = new javax.swing.JButton();
        jbPlaylistCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbPlaylistOk.setText("Ok");
        jbPlaylistOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlaylistOkActionPerformed(evt);
            }
        });

        jbPlaylistCancel.setText("Cancel");
        jbPlaylistCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlaylistCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jcbChoosePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jbPlaylistOk, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbPlaylistCancel)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jcbChoosePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPlaylistOk)
                    .addComponent(jbPlaylistCancel))
                .addGap(24, 24, 24))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-350)/2, (screenSize.height-232)/2, 350, 232);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPlaylistOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlaylistOkActionPerformed
        JSoundsMainWindowViewController.playlistSelectedInCombo=(jcbChoosePlaylist.getSelectedIndex()+1);
        if (!loadPlaylist)
            JSoundsMainWindow.playListNumber=(jcbChoosePlaylist.getSelectedIndex()+1);
        else
        {
            JSoundsMainWindowViewController.loadPlaylist();
            loadPlaylist=false;
        }
        
        restoreFatherWindow();
    }//GEN-LAST:event_jbPlaylistOkActionPerformed

    private void jbPlaylistCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlaylistCancelActionPerformed
       restoreFatherWindow();
       loadPlaylist=false;
    }//GEN-LAST:event_jbPlaylistCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        restoreFatherWindow();
        loadPlaylist=false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistChooser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbPlaylistCancel;
    private javax.swing.JButton jbPlaylistOk;
    private javax.swing.JComboBox jcbChoosePlaylist;
    // End of variables declaration//GEN-END:variables
}
